### ISSUE TITLE
:GoTest crashes nvim

### ISSUE THREAD

**Issue by jawr** [crispgm/nvim-go#12]
If the test does not build correctly, i.e.:

```
[jawr@walnut mxax.v2]$ go test ./...
# github.com/jawr/mxax/internal/http
internal/http/user.go:41:27: s.userService.Register undefined (type mxax.UserService has no field or method Register)
internal/http/user.go:83:14: s.service undefined (type *Server has no field or method service)
FAIL    github.com/jawr/mxax/internal/http [build failed]
ok      github.com/jawr/mxax/internal/inmem     (cached)
ok      github.com/jawr/mxax/mxax       (cached)
FAIL UserRegister attempts to unmarshall a JSON request and then register a user
```

then nvim crashes out:

```
free(): invalid pointer
Aborted (core dumped)
```

**Comment by crispgm** [comment]
@jawr thanks for reporting. I can reproduce and this is so weird.

UPDATE: I can confirm the failing point but dunno what causes that.

Popup window could be closed by config: `require('go').setup({ test_popup = false })` but this also will not show other normal test outputs.

**Comment by jawr** [comment]
If I find some time I would love to have a dig around! Just switched to nvim and love the reasoning and effort of this! Thanks for writing it!

**Comment by crispgm** [comment]
> If I find some time I would love to have a dig around! Just switched to nvim and love the reasoning and effort of this! Thanks for writing it!

I reported to the upstream as well and you may read it to get some idea of what happens <https://github.com/nvim-lua/popup.nvim/issues/14>.

**Comment by crispgm** [comment]
I diagnosed nvim and go test commands then I think go test command returns both stderr and stdout, which causes popup windows crashed nvim. I make a workaround by redirect stderr to stdout. And it basically works well for me.

You may have a try on your use case. @jawr #13

**Comment by jawr** [comment]
That works perfectly crispgm! Thanks for investigating and fixing.

**Comment by crispgm** [comment]
> That works perfectly crispgm! Thanks for investigating and fixing.

I merged. Thanks for your report again. And I think I should continue to push and investigate what really happen to nvim core.
