### ISSUE TITLE
qf open with lint_prompt_style = 'vt'

### ISSUE THREAD

**Issue by kkharji** [crispgm/nvim-go#2]
Hey @crispgm, I'm starting to experiment with go and this tools is awesome. So far there a few issues I noticed:

1. qf opens even though the lint_prompt_style = vt
2. the virtual output is not complete 

![21-03-09_04:50 41](https://user-images.githubusercontent.com/65782666/110406332-1a9d5b00-8093-11eb-94f1-543e5559e28b.png)

Thanks

reproduce:

 `Goerrcheck` on https://paste.sh/vUR94WRa#mGCtjcUgrgmr73wdJ1oa12ph

**Comment by crispgm** [comment]
Thanks for reporting.

Virtual text support is not completed that time. Luckily, it's fixed just now [4324da](https://github.com/crispgm/nvim-go/commit/4324daef78cb5ce9565e271f8d1cadaca92bcf3e) by introducing namespace for virtual text. Run `PlugUpdate nvim-go` with vim-plug or equivalence of other plugin manager to get updated. :)
