### ISSUE TITLE
nvim-dap integration

### ISSUE THREAD

**Issue by cyruseuros** [crispgm/nvim-go#22]
GoDebugTest etc would be a really nice addition

**Comment by crispgm** [comment]
@wurosh this is a good idea. but I do not really use nvim-dap or other debug tools, maybe I will try to figure how it works later.

**Comment by crispgm** [comment]
It seems that nvim-dap runs or debugs program with its own JSON configuration. `:GoDebugTest` would be a mapping of nvim-dap's command. This looks not very necessary for nvim-go.

The idea of nvim-go is to provide a minimal plugin working together with LSP and DAP, neither reimplement nor wrap them. So I recommend you define a command from your config and nvim-dap's config will possibly be project-specific. @wurosh
