### ISSUE TITLE
question: goimports randomly stop working

### ISSUE THREAD

**Issue by deadlysyn** [crispgm/nvim-go#23]
first, thanks for the awesome plugin. used vim-go for years and really happy to have nvim-go while working to convert everything to lua.

i'm sure it's something stupid in my config, but trying to figure out why...  i fire up neovim and goimports works great, adding/removing imports as needed.  after coding awhile, it stops working. no diagnostics above the insert point or anything obvious that should explain it.

have you seen anything like this? my config is largely based on yours with a bit of theprimeagen's. :-)

https://github.com/deadlysyn/dotfiles/tree/main/common/nvim/.config/nvim

TIA for any clues

**Comment by crispgm** [comment]
Hi @deadlysyn thank you for using my configs and this plugin. TBH, I have the same issue and have some ideas about what happens. It happens only if there are errors with language server and neovim does not actually show them at that time. The `BufWritePre` event would not fire sometimes. But I haven't figured it out at the moment. 

You may check whether it applies for your case. And when it happens, you may use `:GoFormat` or `:Goimports` to trigger it manually. I will solve this ASAP as well.

**Comment by crispgm** [comment]
@deadlysyn I think it is kinda solved by this commit cb903af, fixing error prompts. Now when it is not built, it will show `goimports` outputs. You may try updating to the latest version to see whether it occurs again.

**Comment by deadlysyn** [comment]
thanks for the quick response. i've updated and will let you know how it goes.

**Comment by deadlysyn** [comment]
haven't seen the imports issue, but got to code less than hoped over the weekend due to power outage :-(

i will gather more data through the week, but have also noticed another issue.  LSP diagnostic feedback seems to disappear at times.  i haven't noticed this in other langs, but not sure if it is due to nvim-go or my lsp config (still settling into lua).

not sure if you have seen this -- it will show at first, but disappear after save. making additional edits in the file makes it flash back, but disappears again.  i will do more testing on this as well, to see if it behaves the same with nvim-go disabled.

**Comment by crispgm** [comment]
> not sure if you have seen this -- it will show at first, but disappear after save. making additional edits in the file makes it flash back, but disappears again. i will do more testing on this as well, to see if it behaves the same with nvim-go disabled.

This is an (un)expected thing. When we enable auto format, it will write and then ":edit!" to reload the buf, which also triggers nvim-lspconfig's autocmd. `BufReadPost` fires the event to nvim-lspconfig and it re-attaches the lsp client. I think this is the reason.

**Comment by deadlysyn** [comment]
thanks for the detailed response, that makes sense. glad to confirm it's not just me/my config.  feel free to close this issue if you like, not sure if you prefer that or keeping them open as "FAQ" :-)

keep up the good work!

**Comment by crispgm** [comment]
> thanks for the detailed response, that makes sense. glad to confirm it's not just me/my config. feel free to close this issue if you like, not sure if you prefer that or keeping them open as "FAQ" :-)
> 
> keep up the good work!

Thanks for your contribution to this issues. And I think this is not my bug, it looks like an upstream issue. Each time I `:edit`, the diagnostics disappear immediately. Maybe I should spend time on how it works.

**Comment by crispgm** [comment]
@deadlysyn I think I have *solved* it by updating to the latest nightly version of nvim. 🤣
And also I made a commit slightly changed the write behaviors. You may check it if it's possible for to update nvim.

**Comment by deadlysyn** [comment]
confirmed nightly (plus your latest commits) fixed it for me :+1:
