### ISSUE TITLE
jump vim.lsp.diagnostic.goto_prev and vim.lsp.diagnostic.goto_next

### ISSUE THREAD

**Issue by xakep71k** [crispgm/nvim-go#25]
Hello!
Thank you very much. I really enjoy your plugin.
Is it possible to implement jump to linter's warning with lua vim.lsp.diagnostic.goto_prev() and lua vim.lsp.diagnostic.goto_next()?
And see count of warning at airline?

**Comment by crispgm** [comment]
Thanks for your suggestions.

Linters are not `vim.lsp.diagnostic`, they just pop into qflist. If there is a way to put them together (e.g. A qflist manager plugin), I can do that.

Airline support is a good idea. I will check it later.

**Comment by xakep71k** [comment]
This https://github.com/nametake/golangci-lint-langserver are vim.lsp.diagnostic so I can jump to linter's warning with lua vim.lsp.diagnostic.goto_prev() and lua vim.lsp.diagnostic.goto_next(). And it has warning on airline panel. It would be so great if users can specify this integration through opts, for example in lint_prompt_style

**Comment by crispgm** [comment]
> This https://github.com/nametake/golangci-lint-langserver are vim.lsp.diagnostic so I can jump to linter's warning with lua vim.lsp.diagnostic.goto_prev() and lua vim.lsp.diagnostic.goto_next(). And it has warning on airline panel. It would be so great if users can specify this integration through opts, for example in lint_prompt_style

They actually implement a language server for golangci-lint. I think this is not possible for nvim-go right now, because we support multiple third-party linters (golangci-lint, golint(revive), staticcheck, and etc.) and we are not able to implement multiple langservers or an integrated langserver.

If you use golangci-lint, I recommend that you might disable nvim-go auto-lint feature, and setup golangci-lint-langserver. This would perfectly fit your use case.
```lua
require('go').setup({
      auto_lint = false,
})
```

**Comment by crispgm** [comment]
@xakep71k I just added a commit which can implement issues count for various status line plugins. For airline, please add this to your `.vimrc` or Lua equivalent config:
```vimscript
    function! LintIssuesCount()
        if exists('g:nvim_go#lint_issues_count')
            return g:nvim_go#lint_issues_count
        endif
    endfunction
    call airline#parts#define_function('nvim_go', 'LintIssuesCount')
    call airline#parts#define_condition('nvim_go', '&filetype == "go"')
    let g:airline_section_warning = airline#section#create_right(['nvim_go'])
```

**Comment by crispgm** [comment]
And also there are some examples here: <https://github.com/crispgm/nvim-go#statusline-count>
