### ISSUE TITLE
[Feature request]: enable adding tags to test

### ISSUE THREAD

**Issue by tempegarit** [crispgm/nvim-go#35]
Hi! Thanks for this awesome plugin.

Some tests require `tags` to run. Example:
`go test -run=TestCreateUser -tags=sqlite_fts5`

Is it posible to add a feature so that we can pass `tags` as arguments like `:GoTestFunc -tags=sqlite_fts5`?
It would be cool if we can pass `tags` to `:GoTest` and other form of test as well.

Thanks.

**Comment by crispgm** [comment]
@tempegarit I think you may try `test_flags`:
```lua
require('go').setup({
   test_flags = {'-tag=sqlite_fts5'},
})
```

**Comment by tempegarit** [comment]
It works! Thanks mate!
