### ISSUE TITLE
GoInstallBinaries does not install gopls

### ISSUE THREAD

**Issue by assistcontrol** [crispgm/nvim-go#36]
`:GoInstallBinaries` does not install `gopls`, because it tries to install `gopls@latest@latest`

In `lua/go/config.lua`:

    { name = 'gopls', src = 'golang.org/x/tools/gopls@latest' }

In `lua/go/install.lua`, in `build_cmd()`:

    src = tool.src .. '@latest'

Dropping the `@latest` in `config.lua` fixes the installation.

**Comment by crispgm** [comment]
@assistcontrol hello, which `go version` does you use?

For, go 1.17+, it's `go install golang.org/x/tools/gopls@latest`. Otherwise, it's `go get golang.org/x/tools/gopls`.

**Comment by assistcontrol** [comment]
> @assistcontrol hello, which `go version` does you use?
> 
> For, go 1.17+, it's `go install golang.org/x/tools/gopls@latest`. Otherwise, it's `go get golang.org/x/tools/gopls`.

I'm using 1.17.6 (go version go1.17.6 darwin/amd64).

The problem is that it isn't installing `go install golang.org/x/tools/gopls@latest`, it's trying to run `go install golang.org/x/tools/gopls@latest@latest` which fails.

**Comment by crispgm** [comment]
> > @assistcontrol hello, which `go version` does you use?
> > For, go 1.17+, it's `go install golang.org/x/tools/gopls@latest`. Otherwise, it's `go get golang.org/x/tools/gopls`.
> 
> I'm using 1.17.6 (go version go1.17.6 darwin/amd64).
> 
> The problem is that it isn't installing `go install golang.org/x/tools/gopls@latest`, it's trying to run `go install golang.org/x/tools/gopls@latest@latest` which fails.

Thanks for your explanation. It's my bug.
