### ISSUE TITLE
Error raised when both formatting and linting fire on write

### ISSUE THREAD

**Issue by telemachus** [crispgm/nvim-go#38]
(Thanks for nvim-go. I've just started using it, and I appreciate your work on it.) I've run into a situation where the default settings lead to an error.

Here's how to reproduce. (What follows assumes default settings: both `auto_format` and `auto_lint` are true; formatting uses `goimports` and linting uses `revive`.)

1. Open a file. (I don't think it needs to be new, but…)
2. Enter the following. (This code may seem contrived, but I don't think the situation is. All that's required is that you haven't entered some of your imports yet, and you have something that the linter will complain about.)

        package main

        var ErrNoSuch = errors.New("no such error")

        func main() {
	        fmt.Printf("%v\n", ErrNoSuch)
        }
4. That should lead to something like the following error:
```shell
....config/nvim/pack/bundle/start/nvim-go/lua/go/format.lua:33: Vim(edit):E32: No file name
stack traceback:
[C]: in function 'nvim_exec'
....config/nvim/pack/bundle/start/nvim-go/lua/go/format.lua:33: in function <....config/nvim/pack/bundle/start/nvim-go/lua/go/format.lua:30>
```

I think that the linter and the formatter end up competing with one another. The linter wants to complain that `ErrNoSuch` should have a comment because it's exported, and the formatter wants to add imports. But by the time you reach line 32 of `format.lua` (`vim.api.nvim_exec('edit', true)`), the linter has placed you in the location list. There's no filename there, so calling `edit` leads to a "No file name" error.

I'm not sure whether my diagnosis is right, and the problem may be too rare to worry about, but I wanted to let you know.

**Comment by crispgm** [comment]
@telemachus Thanks for your detail information describing the case. Do you have the latest version? Personally, I have the same error on some random cases before but I think it's fixed. Theoretically it won't happen because those two events are in order.

**Comment by telemachus** [comment]
I am using the latest version (68d6908, as of March 14), and I'm still seeing the same problem if I use the input I showed above.

I understand if it's not a priority, but I'd love to know whether you do or don't have the problem with that input. (Maybe it's some other setting on my end, but I'm not sure what.)

**Edit**: to satisfy my own curiosity, I removed all plugins other than nvim-go, plenary.vim, and popup.nvim, and I also removed everything from my `init.lua` file other than the setup block for `nvim-go`. Even so, I still get an error in a case like that above where `goimports` and `revive` seem to trip over one another.

**Comment by crispgm** [comment]
@telemachus sounds weird. This happens when loclist bump out earlier than `BufWritePre`, which triggers `:GoFormat`. Something like LSP Diagnostics may cause this.

Would you mind posting your reproduction steps here? With an example of your file (or just new file?) and your minimal init.lua?

**Comment by telemachus** [comment]
> Would you mind posting your reproduction steps here? With an example of your file (or just new file?) and your minimal init.lua?

Sure. The init.lua is this:

```lua
require('go').setup({
    -- auto commands
    auto_format = true,
    auto_lint = true,
    -- linters: revive, errcheck, staticcheck, golangci-lint
    linter = 'revive',
    -- linter_flags: e.g., {revive = {'-config', '/path/to/config.yml'}}
    linter_flags = {},
    -- lint_prompt_style: qf (quickfix), vt (virtual text)
    lint_prompt_style = 'qf',
    -- formatter: goimports, gofmt, gofumpt
    formatter = 'goimports',
})
```

I have no other initialization files, and the only plugins I've installed are nvim-go, plenary.nvim, and popup.nvim.

Here is the file I'm using to test (`foo.go`).

```go
package main

var ErrNoSuch = errors.New("no such error")

func main() {
	fmt.Printf("%v", ErrNoSuch)
}
```

To reproduce, just open that file and enter `:w`. If I do that, I get an error. Here's the messages output:

```shell
"foo.go" 7L, 104B written
GoFormat Success
....config/nvim/pack/bundle/start/nvim-go/lua/go/format.lua:33: Vim(edit):E32: No file name
stack traceback:
^I[C]: in function 'nvim_exec'
^I....config/nvim/pack/bundle/start/nvim-go/lua/go/format.lua:33: in function <....config/nvim/pack/bundle/start/nvim-go/lua/go/format.lua:30>
```

I don't know if this matters, but notice that it says **7L** written. That message doesn't yet have the five lines that `goimports` add. 

I'm on macOS 12.2.1 and using iTerm2 3.4.15. Here's the output of `nvim --version`:

```shell
NVIM v0.7.0-dev+1231-g6170574d2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by telemachus@paronoff

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/Users/telemachus/local/neovim/share/nvim"

Run :checkhealth for more info
```

And here's the output of `checkhealth`:

```shell

go: require("go.health").check()
========================================================================
## Binaries
  - INFO: Go installed.
  - INFO: Tool installed: gopls
  - INFO: Tool installed: golint
  - INFO: Tool installed: revive
  - INFO: Tool installed: goimports
  - INFO: Tool installed: gofumpt
  - INFO: Tool installed: errcheck
  - INFO: Tool installed: staticcheck
  - ERROR: Missing tool: golangci-lint
  - ERROR: Missing tool: gomodifytags
  - ERROR: Missing tool: quicktype
  - OK: No issues found

nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='iTerm.app'
  - INFO: $COLORTERM='truecolor'

provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 3 provider (optional)
  - INFO: pyenv: Path: /Users/telemachus/.pyenv/libexec/pyenv
  - INFO: pyenv: Root: /Users/telemachus/.pyenv
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /Users/telemachus/.pyenv/versions/3.10.1/bin/python3
  - INFO: Python version: 3.10.1
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - WARNING: `node` and `npm` (or `yarn`) must be in $PATH.
    - ADVICE:
      - Install Node.js and verify that `node` and `npm` (or `yarn`) commands work.

## Perl provider (optional)
  - ERROR: perl provider error:
    - ADVICE:
      - "Neovim::Ext" cpan module is not installed

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - INFO: LSP log level : WARN
  - INFO: Log path: /Users/telemachus/.cache/nvim/lsp.log
  - INFO: Log size: 25 KB

vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 14
  - OK: Loaded parser for c: ABI version 13
```

**Comment by crispgm** [comment]
@telemachus It's pretty weird that I cannot reproduce following your steps. I opened your `foos.go` with minimal vim config and Neovim v0.7.0-dev+1262-g5a8bf31d3. It works good, where `goimports` works properly and `revive` should the uncommented issue.

**Comment by telemachus** [comment]
> It's pretty weird that I cannot reproduce following your steps.

Thanks for getting back to me. That is weird—and a little frustrating for me (though obviously not your fault!).

Here's one more question, but you're welcome to close this if you want. Do you have any other (optional) plugins that work with or help with nvim-go besides plenary.nvim and popup.nvim? Maybe my problem is that my set-up is too minimal? Thanks.

**Comment by crispgm** [comment]
> > It's pretty weird that I cannot reproduce following your steps.
> 
> Thanks for getting back to me. That is weird—and a little frustrating for me (though obviously not your fault!).
> 
> Here's one more question, but you're welcome to close this if you want. Do you have any other (optional) plugins that work with or help with nvim-go besides plenary.nvim and popup.nvim? Maybe my problem is that my set-up is too minimal? Thanks.

I am so sorry that I cannot help you get this resolved. If you'd like to show lint issues inline, here is a workaround, you may change `lint_prompt_style=vt` to show it with nvim virtual text.

For similar plugin, you may definitely use vim-go instead. It actually inspire me to make nvim-go because I use it before. But I want to make a new plugin because vim-go just does not show go test result anywhere.

**Comment by telemachus** [comment]
Thanks for the tips. I'm not going to switch. I'm happy with something minimal. For now, I'll probably set autolinting to false. I can also try `link_prompt_style=vt`. Thanks for the tips.

**Comment by crispgm** [comment]
@telemachus just remember here might be a workaround, which does not focus on loclist by the following autocmd. You may have a last try.
```viml 
augroup NvimGo
  autocmd!
  autocmd User NvimGoLintPopupPost wincmd p
augroup END
```

**Comment by telemachus** [comment]
@crispgm That works perfectly: thanks! (I'll close this now. Thanks again.)

**Comment by smlx** [comment]
FWIW I also have this bug and have worked around it successfully using https://github.com/crispgm/nvim-go/issues/38#issuecomment-1072951349
