### ISSUE TITLE
Question about a possible pull request

### ISSUE THREAD

**Issue by telemachus** [crispgm/nvim-go#39]
First, thanks for nvim-go.

When you format a buffer using goimports, the cursor is liable to jump around (because lines can be added, removed, or both). I find this a bit distracting. There's a way to prevent the jump, and it's not a great deal of code, but it does add a bit to the complexity of `format.lua`. I've been using the following, and I wondered if you would consider a pull request to add this to nvim-go. Thanks for considering it.

```diff
diff --git a/lua/go/format.lua b/lua/go/format.lua
index 68a1f9c..221b4b9 100644
--- a/lua/go/format.lua
+++ b/lua/go/format.lua
@@ -17,6 +17,17 @@ function M.format(fmt)
     return pcall(M[formatter])
 end
 
+local function get_new_line_nr(original_file_len)
+    local line_offset = vim.fn.line('$') - original_file_len
+    local cur_line_nr = vim.fn.line('.')
+    return cur_line_nr + line_offset
+end
+
+local function get_new_col_nr(new_line, original_line, original_col_nr)
+    local col_offset = vim.fn.len(new_line) - vim.fn.len(original_line)
+    return original_col_nr + col_offset
+end
+
 local function do_fmt(formatter, args)
     if not util.binary_exists(formatter) then
         return
@@ -25,6 +36,9 @@ local function do_fmt(formatter, args)
     local file_path = vim.api.nvim_buf_get_name(buf_nr)
     local view = vim.fn.winsaveview()
     vim.api.nvim_exec('noautocmd write', true)
+    local original_file_len = vim.fn.line('$')
+    local original_line = vim.fn.getline('.')
+    local original_col_nr = vim.fn.col('.')
     local cmd = system.wrap_file_command(formatter, args, file_path)
     vim.fn.jobstart(cmd, {
         on_exit = function(_, code, _)
@@ -32,6 +46,14 @@ local function do_fmt(formatter, args)
                 output.show_success('GoFormat', 'Success')
                 vim.api.nvim_exec('edit', true)
                 vim.fn.winrestview(view)
+                local new_line_nr = get_new_line_nr(original_file_len)
+                local new_line = vim.fn.getline(new_line_nr)
+                local new_col_nr = get_new_col_nr(
+                    new_line,
+                    original_line,
+                    original_col_nr
+                )
+                vim.fn.cursor(new_line_nr, new_col_nr)
             end
         end,
         on_stderr = function(_, data, _)
```

**Comment by crispgm** [comment]
This sounds good. Let me have a look at the effect.

**Comment by crispgm** [comment]
@telemachus I tested it with a file. I think it did not accurately calculate the offset. From the codes, it counted the file increments as the offset, is it correct?

**Comment by telemachus** [comment]
> I tested it with a file. I think it did not accurately calculate the offset. From the codes, it counted the file increments as the offset, is it correct?

Yes, if the cursor starts on line 7 and `goimports` adds five lines, then the cursor should end up on line 12 to be on the same line as it began. There are some edge cases, I think. For example, things will go wrong if the cursor begins on a line *above* where `goimports` adds lines or if (weirdly) there were blank lines at the bottom of the file before `goimports` does its work. But [the basic method follows the one in vim-go](https://github.com/fatih/vim-go/blob/master/autoload/go/fmt.vim#L81), and in my experience so far it works.

But maybe I've made a mistake or I'm confused. Can you give me an example where it didn't work?

**Comment by crispgm** [comment]
@telemachus Thanks for the idea and information. I think it pretty good but I'd like to add an option on this feature so that users with no need could opt it out.

And would you mind opening a pull request?

**Comment by telemachus** [comment]
> I think it pretty good but I'd like to add an option on this feature so that users with no need could opt it out.

That makes sense. Any suggestions about the option's name? Also, should the option be true or false by default?

> And would you mind opening a pull request?

Yup. I'll add the option and the diff and then make a pull request for you to review and adjust.

**Comment by telemachus** [comment]
Hi, this isn't a huge deal, but I'm confused. The [related pull request](https://github.com/crispgm/nvim-go/pull/41) is still open.

Did you implement this feature yourself or decide you didn't want it after all?

**Comment by crispgm** [comment]
> Hi, this isn't a huge deal, but I'm confused. The [related pull request](https://github.com/crispgm/nvim-go/pull/41) is still open.
> 
> Did you implement this feature yourself or decide you didn't want it after all?

Sorry I forgot to submit the review and there is some minor issues to be fixed before merging. You may please check it.

**Comment by telemachus** [comment]
> Sorry I forgot to submit the review and there is some minor issues to be fixed before merging. You may please check it.

Done. Let me know if you want me to change anything else.
