### ISSUE TITLE
Feature Request: add support for goimpl & gotests

### ISSUE THREAD

**Issue by marcomayer** [crispgm/nvim-go#46]
Thanks for the plugin, it's very close to what I need to move away from go.nvim which is too overloaded for me. The only things I'd love to see integrated at some point are goimpl (https://github.com/sasha-s/goimpl) and gotests (https://github.com/cweill/gotests) support. 

I think both can be implemented similar to :GoQuicktype. If I find the time I'll come up with a PR myself.

**Comment by crispgm** [comment]
👍🏻 The idea is great. I investigate the functions provided by vim-go and VSCode go plugin. Those two are common functions. But for me, I rarely use that so I did not include them in the early release.

**Comment by marcomayer** [comment]
Added gotests support: #47
