### ISSUE TITLE
Map `q` to close floating windows

### ISSUE THREAD

**Issue by diktomat** [crispgm/nvim-go#49]
To close floating windows (like after `:GoTest`) one currently has to use `:q` or `:close`. It is I think convention now to map `q` to close floats, as seen in Neovims original LSP Hover or ellisonleao/glow.nvim, to name just two examples off the top of my head. Would be great if nvim-go could support that too.

**Comment by crispgm** [comment]
@d12bb Thanks for the suggestion. Please update and have a try :)

**Comment by diktomat** [comment]
Wow, that was quick! Works fine, thank you 👍
