### ISSUE TITLE
Feature Request: Add go-vet

### ISSUE THREAD

**Issue by tomleewu** [crispgm/nvim-go#54]
Hi there, I'm enjoying this plugin. Would you consider adding in a command for go vet? 

I would appreciate it!

**Comment by crispgm** [comment]
Hello Tom,

I was investigating this topic. It seems that `gopls` actually contains `go vet`'s analyzers.
- https://pkg.go.dev/cmd/vet
- https://github.com/golang/tools/blob/master/gopls/doc/analyzers.md

**Comment by tomleewu** [comment]
Oh I see, so `gopls` supersets `go vet`'s analyzers. I didn't realize that, thank you! I will close this issue now.
