### ISSUE TITLE
Option to avoid npm dependency

### ISSUE THREAD

**Issue by smlx** [crispgm/nvim-go#57]
Hi, this is a great plugin. Thanks for making it!

One issue I ran into was running `GoInstallBinaries` failed due to the dependency on `npm` and not having `npm` installed locally.

It would be great if there was some way to configure the plugin to avoid the dependency.

My workaround for now is to manually delete [this line](https://github.com/crispgm/nvim-go/blob/099a3ff71bd7f3df30ced986154d35b1756c1277/lua/go/config.lua#L55).

**Comment by crispgm** [comment]
The JSON generation feature is powered by quicktype and it's written in Node. So `npm`, `pnpm` or `yarn` is required to install that tool.

If you intend to do so, `GoQuickType` will fail. I think it okay to add an option to disable installation of certain dependency though.
