### ISSUE TITLE
Linter produces spurious warning about package comment

### ISSUE THREAD

**Issue by smlx** [crispgm/nvim-go#59]
If I run `:GoLint` or have auto-lint enabled, I get a package warning like:
```
internal/core/rotate.go|1 col 1 warning| should have a package comment
```

This happens even if another `.go` file in the same package already has a package comment.

By running `revive` manually I think I can understand what's happening. Passing the package as a lint target works correctly:
```
$ revive .
$
```
But targeting just the single `.go` file produces the spurious warning:
```
$ revive rotate.go
rotate.go:1:1: should have a package comment
$
```

I see there is already [code to target the package rather than the file](https://github.com/crispgm/nvim-go/blob/6775cba94504e69fa9c8816cc89e37479ef4300a/lua/go/lint.lua#L82-L85) for other linters. Maybe that logic needs to be extended to include `revive`?

**Comment by crispgm** [comment]
Thank you for your feedback. Your suggestion is possible. We may fix this soon.
