### ISSUE TITLE
Error When i open one .go and other file

### ISSUE THREAD

**Issue by cxykhaos** [crispgm/nvim-go#61]
I wirte code in other file trigger Error When i open one .go file and other file

**Comment by crispgm** [comment]
Would you mind showing your error text or screenshot? I guess Go toolchain only works with `go.mod`.

**Comment by cxykhaos** [comment]
![image](https://user-images.githubusercontent.com/60059661/201611637-2b8050a2-6bbd-49c1-afef-d9ecfa2b7a42.png)

**Comment by cxykhaos** [comment]
![image](https://user-images.githubusercontent.com/60059661/201611679-55d2be66-2779-4a03-ac3f-0e5798e9c527.png)

**Comment by crispgm** [comment]
Okay, from what you've post, you opened one Go file and another Python?

**Comment by cxykhaos** [comment]
yes, It's annoying to trigger every time you enter virtual mode

**Comment by cxykhaos** [comment]
yes, It's annoying to trigger every time you enter normal mode

**Comment by cxykhaos** [comment]
This is triggered not only in python, but also in other configuration type files

**Comment by cxykhaos** [comment]
Error executing vim.schedule lua callback: UnhandledPromiseRejection with the reason:
RPC[Error] code_name = unknown, code = 0, message = "cannot parse non-Go file file:///Users//**/workplace//scripts/**/**.py"

**Comment by crispgm** [comment]
> Error executing vim.schedule lua callback: UnhandledPromiseRejection with the reason: RPC[Error] code_name = unknown, code = 0, message = "cannot parse non-Go file file:///Users//**/workplace//scripts/**/**.py"

What did you do before prompting this error message? Any `GoXXXX` commands or simply `:w`?

**Comment by cxykhaos** [comment]
NO, i only from  insert mode to normal mode

**Comment by cxykhaos** [comment]
look like gopls（lsp） cause it

**Comment by crispgm** [comment]
> look like gopls（lsp） cause it

`gopls` is not controlled by `nvim-go`. Do you use `neovim/lspconfig`?

**Comment by cxykhaos** [comment]
yes
